openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: http://localhost:9090/auth/
tags:
  - name: utente
    description: Operations about user management and authentication
paths:
  /cerca/{email}:
    get:
      tags:
        - utente
      operationId: getHttpUser
      parameters:
        - name: email
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: succesful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UtenteHttp'
      security:
        - basicAuth: [ ]
  /currentUtente:
    post:
      tags:
        - utente
      operationId: getCurrentUtente
      requestBody:
        description: chiave unica
        content:
          application/json:
            schema:
              type: string
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UtenteHttp'
        '404':
          description: utente non trovato
  /getUtenti:
    get:
      tags:
        - utente
      operationId: getAllUtenti
      parameters:
        - name: page
          in: query
          description: pagina
          required: false
          schema:
            type: integer
            format: int32
            default: 0
        - name: size
          in: query
          description: size
          required: false
          schema:
            type: integer
            format: int32
            default: 5
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Page'

  /updateUtente/{userKey}:
    post:
      tags:
        - utente
      operationId: updateUtente
      parameters:
        - name: userKey
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: dati utente
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UtenteRequest'
      responses:
        '200':
          description: uuid utente
          content:
            application/json:
              schema:
                type: string
        '404':
          description: utente non trovato

  /creaUtente:
    post:
      tags:
        - utente
      operationId: creaUtente
      requestBody:
        description: dati utente
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UtenteRequest'
      responses:
        '200':
          description: uuid utente
          content:
            application/json:
              schema:
                type: string
  /deleteUser:
    delete:
      tags:
        - utente
      operationId: deleteUtente
      parameters:
        - name: userKey
          in: query
          schema:
            type: string
      responses:
        '200':
          description: succesful
        '404':
          description: utente non esistente


components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic

  schemas:
    UtenteHttp:
      type: object
      properties:
        nome:
          type: string
        cognome:
          type: string
        email:
          type: string
        password:
          type: string
        telefono:
          type: string
        tipoUtente:
          type: string
        userKey:
          type: string

    UtenteRequest:
      $ref: './api.yaml#/components/schemas/UtenteRequest'

    Page:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/UtenteHttp'
        pageNumber:
          type: integer
          format: int32
        pageSize:
          type: integer
          format: int32
        totalElements:
          type: integer
          format: int32
        totalPages:
          type: integer
          format: int32
        last:
          type: boolean